### ISSUE TITLE
Different result with gcc in tests/char.c

### ISSUE THREAD

**Issue by yodalee** [jserv/amacc#23]
In test file `tests/char.c`, the amacc execution result of following code:

```
p = malloc(128);
p[0] = -1;
v = p[0];
printf("%x %d %d %x\n", p[0], p[0], v, p[1]);
```

is different to gcc.
amacc generates `ffffffff -1 -1 65` while gcc generates `ff 255 255 65`
Not sure is this an issue or not. It may related to that amacc handle `char` as `signed char`, not sure for now.

**Comment by jserv** [comment]
@loganchien, Can you please give some hints?

**Comment by loganchien** [comment]
Either (a) removing `-fsigned-char` from Makefile or (b) adding `-fsigned-char` to `gccparams` in `runtest.py` will fix that test.

TL;DR

`amacc` uses following trick to decide whether a `char` should be treated as `signed char` or `unsigned char`:

```
630     neg_char = 255;
631     neg_int = neg_char;
```

But this uses an assumption that compiler hosting environment (the environment which runs the compiler) is equal to the target environment (the environment which runs the code generated by the compiler).  This may not be true.

BTW, according to ARM ABI, `char` defaults to `unsigned char`.  One should specify `-fsigned-char` if `signed char` is preferred.
