### ISSUE TITLE
Implement standalone interpreter for generated IR

### ISSUE THREAD

**Issue by jserv** [jserv/amacc#32]
At present, AMaCC translates C source into internal bytecode form on which code generator depends for Arm machine code. The argument `-s` is to generate bytecode from parsing tree. Here is the example:
```
$ ./amacc -s tests/hello.c 
1: #include <stdio.h>
2: 
3: int main()
4: {
5:     printf("hello, world\n");
    ENT  0
    IMM  -568971248
    PSH 
    PRTF
    ADJ  1
6:     return 0;
    IMM  0
    LEV 
7: }
```

Branch [interpreter](https://github.com/jserv/amacc/tree/interpreter) provides incomplete interpreter support, which can accepts bytecode. It would be great if we can take the standalone interpreter to validate AMaCC internally.

Reference: [Write a C interpreter](https://github.com/lotabout/write-a-C-interpreter/tree/master/tutorial/en)

**Comment by splasky** [comment]
The branch interpreter is outdated. Maybe we can close it.

**Comment by jserv** [comment]
This issue is invalid per @splasky requested.
