### ISSUE TITLE
The undefined behavior of AMaCC is different from gcc

### ISSUE THREAD

**Issue by splasky** [jserv/amacc#39]
On my platform:
```
ubuntu 18.04
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
```
Left shift operator inside gcc with negative argument will become right shift,but AMaCC will set the result to 0.
Do we need to change AMaCC to keep the behavior consistent with gcc?
This is the failure message after check test:
```
FAIL: test_shift (__main__.TestCC_SC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtest.py", line 55, in test
    self.assertEqual(amacc_out.decode('utf-8'), gcc_out.decode('utf-8'))
AssertionError: '1 <<[70 chars]-1 = 0\n-1 << 1 = fffffffe\n-1 << 0 = ffffffff[197 chars]68\n' != '1 <<[70 chars]-1 = 2\n-1 << 1 = fffffffe\n-1 << 0 = ffffffff[197 chars]68\n'
  1 << 0 = 1
  1 << 2 = 4
  0 << 4 = 0
  1 << 31 = 80000000
  1 << 32 = 0
- 4 << -1 = 0
?           ^
+ 4 << -1 = 2
?           ^
  -1 << 1 = fffffffe
  -1 << 0 = ffffffff
  4 >> 1 = 2
  4 >> 5 = 0
  0x80000000 >> 31 = ffffffff
  -1 >> 2 = ffffffff
  -1091119768 - -1091119766 = -2(fffffffe)
  a = f6d5680c, b = bef6d568, c = fff6d568
  a = 76d5680c, b = bef6d568, c = bef6d568
```

**Comment by jserv** [comment]
The known issue was caused by character signedness as @loganchien mentioned in PR #26 .

**Comment by splasky** [comment]
Hi @alapha23 , on my platform the issue is still occur.
In my experience, AMaCC doesn't support shift negative,so the result will be decided by your machine.
The `-fsigned-char` is for load char instruction to decided the char signedness.
For the gcc shift negative value, you can refer to https://gcc.gnu.org/ml/gcc-help/2015-12/msg00010.html

**Comment by jserv** [comment]
@splasky, How about software emulation of shift negative? Thus, we could have the consistent results as gcc does.

**Comment by alapha23** [comment]
@splasky Thank you for the reply. Good to confirm. 

@jserv I also think software emulation should be a good approach. 
Regarding a possible solution, if I get you right, perhaps we could add semantics check to line 618 of [amacc.c](https://github.com/jserv/amacc/blob/master/amacc.c)
```=c
case Shl: next(); *++e = PSH; expr(Add); *++e = SHL; ty = INT; break;
``` 

What do you think?
