### ISSUE TITLE
Reorder opcode enumeration

### ISSUE THREAD

**Issue by jserv** [jserv/amacc#58]
Recent div/mod operator support breaks the classification of opcode enumeration:
```c
/* system call shortcuts */
OPEN,READ,WRIT,CLOS,PRTF,MALC,FREE,MSET,MCMP,MCPY,MMAP,DSYM,BSCH,STRT,DLOP,DIV,MOD,EXIT,
```

Both `DIV` and `MOD` should be moved to somewhere nearby `SUB` and `MUL`.

**Comment by HPCguy** [comment]
Closed by #80
